CREATE DATABASE GESTION_VENTAS
USE GESTION_VENTAS

CREATE TABLE PRODUCTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CODIGO CHAR(8) NOT NULL, 
	NOMBRE VARCHAR(40) NOT NULL,
	MARCA VARCHAR(40) NOT NULL,
	MODELO VARCHAR(40) NOT NULL,
	PRECIO DOUBLE NOT NULL,
	CANTIDAD INT NOT NULL
)

TRUNCATE TABLE PRODUCTO
SELECT * FROM PRODUCTO 


CREATE TABLE CLIENTES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO CHAR(9) NOT NULL,
	RUC CHAR(11) NOT NULL
)

TRUNCATE TABLE clientes
SELECT * FROM CLIENTES

CREATE TABLE PROVEEDORES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO CHAR(9) NOT NULL
)

TRUNCATE TABLE PROVEEDORES;
SELECT * FROM PROVEEDORES
